server:
  port: 8080
  shutdown: "graceful"
  forward-headers-strategy: "framework"
  tomcat:
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB

spring:
  main:
    banner-mode: "off"
  application:
    name: project
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
    mode: HTML
  servlet:
    multipart:
      enabled: true
      max-file-size: 80MB
      max-request-size: 100MB
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

project:
  semantic-engine:
    enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,prometheus,processes
  health:
    mail:
      enabled: false
    livenessState:
      enabled: true
    readinessstate:
      enabled: true
  server:
    port: 7070
